/** Startseite (Säule) in beiden Sprachen. Alle Rechtswerte über h.P, nie fest im Text. */
import type { FAQ, Helpers } from '../lib/guide-types';
import { BMF_FAELLE, BMF_BETRAEGE, BMF_MIN, BMF_MAX, BMF_DATUM, beispiel, lstFreiBis } from '../lib/pruefung';
import { svLaufend } from '../lib/engine/lohn';

const A = beispiel(3000), W = beispiel(3000, true), B18 = beispiel(1800);
const WD = svLaufend(3000, true).summe - svLaufend(3000).summe;
const FREI = lstFreiBis();
const ST = (h: Helpers) => h.P.sonderzahlungen.stufen as [number, number][];
const S6 = (h: Helpers) => h.pct(ST(h)[1][1], 0), S27 = (h: Helpers) => h.pct(ST(h)[2][1], 0), S35 = (h: Helpers) => h.pct(ST(h)[3][1], 2);
const G25 = (h: Helpers) => h.eur(ST(h)[0][0] + ST(h)[1][0]), G50 = (h: Helpers) => h.eur(ST(h)[0][0] + ST(h)[1][0] + ST(h)[2][0]);

interface HomeText { title: string; description: string; h1: string; intro: string; resume: (h: Helpers) => string; faqs: (h: Helpers) => FAQ[]; body: (h: Helpers) => string }

export const HOME: Record<'de' | 'en', HomeText> = {
  de: {
    title: 'Brutto-Netto-Rechner Österreich 2026: Lohn genau berechnen',
    description: 'Brutto-Netto-Rechner Österreich 2026: Lohnsteuer, SV, 13. und 14. Gehalt mit Jahressechstel, Pendlerpauschale und Familienbonus, geprüft am BMF-Rechner.',
    h1: 'Brutto-Netto-Rechner Österreich 2026',
    intro: 'Vom Bruttogehalt zum Netto auf dem Konto: Sozialversicherung, Lohnsteuer, Urlaubszuschuss und Weihnachtsremuneration, Monat für Monat nach den Werten 2026.',
    resume: (h) => `Bei ${h.eur(A.bruttoJahr / 14)} brutto im Monat bleiben 2026 in Oberösterreich, Tirol oder der Steiermark ${h.eur(A.nettoMonat, 2)} netto: ${h.pct(A.svMonat / 3000, 2)} Sozialversicherung und ${h.eur(A.lstMonat, 2)} Lohnsteuer gehen ab. Der Urlaubszuschuss und die Weihnachtsremuneration bringen je rund ${h.eur(Math.round(A.uzNetto / 10) * 10)} netto, weil der 13. und 14. Bezug nach Abzug eines Freibetrags von ${h.eur(h.P.sonderzahlungen.freibetrag)} nur mit ${S6(h)} besteuert wird. Das gilt, solange beide Zahlungen in das Jahressechstel passen, also ein Sechstel der laufenden Bezüge. Steigt das Gehalt im Laufe des Jahres oder beginnt die Arbeit erst im Sommer, verschiebt sich diese Grenze, und genau diesen Fall rechnen die meisten Rechner nicht. Die Tarifgrenzen sind 2026 um ${h.pct(h.P.tarif.indexierung_2026, 2)} gestiegen, der Pendlereuro hat sich auf ${h.eur(h.P.absetzbetraege.pendlereuro_je_km)} je Kilometer verdreifacht, und in Wien kostet der Wohnbauförderungsbeitrag seit Jänner ${h.pct(h.P.sv.dn.wf_wien, 2)} statt ${h.pct(h.P.sv.dn.wf, 1)}. Unser Rechner wendet all das an und stimmt in ${BMF_FAELLE} Vergleichsfällen auf den Cent mit dem Brutto-Netto-Rechner des Finanzministeriums überein.`,
    faqs: (h) => [
      { q: 'Wie viel bleibt mir 2026 von 3.000 Euro brutto?', a: `In jedem Bundesland außer Wien ${h.eur(A.nettoMonat, 2)} netto im Monat; in Wien ${h.eur(W.nettoMonat, 2)}, weil der Wohnbauförderungsbeitrag dort seit Jänner 2026 ${h.pct(h.P.sv.dn.wf_wien, 2)} statt ${h.pct(h.P.sv.dn.wf, 1)} beträgt. Dazu kommen Urlaubszuschuss und Weihnachtsremuneration mit je rund ${h.eur(Math.round(A.uzNetto / 10) * 10)} netto. Aufs Jahr gerechnet sind das ${h.eur(A.nettoJahr)} netto aus ${h.eur(A.bruttoJahr)} brutto, ohne Kinder und ohne Pendlerpauschale, nach den Werten des BMF-Rechners 2026.` },
      { q: 'Warum ist mein Weihnachtsgeld höher besteuert als das Urlaubsgeld?', a: `Meist ist es umgekehrt: Der Freibetrag von ${h.eur(h.P.sonderzahlungen.freibetrag)} wird mit der ersten Sonderzahlung verbraucht, dem Urlaubszuschuss. Die Weihnachtsremuneration wird daher vom ersten Euro an mit ${S6(h)} besteuert. Liegt sie zusätzlich über dem Jahressechstel, etwa nach einer Gehaltserhöhung im Herbst oder bei einer Prämie, wird der Überhang wie ein Monatsgehalt nach dem Tarif versteuert. Die Rechnung steht in § 67 EStG.` },
      { q: 'Rechnet der Rechner mit 12 oder 14 Gehältern?', a: `Standard sind 14 Bezüge: zwölf Monatsgehälter, der Urlaubszuschuss im Juni und die Weihnachtsremuneration im November, wie es die meisten Kollektivverträge vorsehen. Unter „Sonderzahlungen“ lässt sich auf eine oder keine umstellen, etwa für freie Dienstnehmer. Wer ein Jahresbrutto eingibt, bekommt es durch ${12 + 2} geteilt, also das Monatsgehalt, das dieses Jahresbrutto mit 14 Bezügen ergibt.` },
      { q: 'Zählt mein Bundesland bei der Lohnberechnung?', a: `Für den Arbeitnehmer nur in Wien: Dort beträgt der Wohnbauförderungsbeitrag seit 1. Jänner 2026 ${h.pct(h.P.sv.dn.wf_wien, 2)} des Bruttos, in den übrigen acht Ländern ${h.pct(h.P.sv.dn.wf, 1)}. Bei ${h.eur(3000)} brutto sind das ${h.eur(WD, 2)} mehr Abzug im Monat. Lohnsteuer, Krankenversicherung und Pensionsversicherung sind österreichweit gleich. Beim Dienstgeber unterscheidet sich zusätzlich der Zuschlag zum Dienstgeberbeitrag je Land.` },
      { q: 'Ab welchem Einkommen zahlt man in Österreich Lohnsteuer?', a: `Bis ${h.eur(h.P.tarif.grenzen[0])} steuerpflichtigem Jahreseinkommen fällt keine Einkommensteuer an. Mit 14 Bezügen, Werbungskostenpauschale und Verkehrsabsetzbetrag bleibt man 2026 bis etwa ${h.eur(FREI)} brutto im Monat ohne Lohnsteuer, bei ${h.eur(1800)} sind es ${h.eur(B18.lstMonat, 2)}. Sozialversicherung zahlt man dagegen schon ab ${h.eur(h.P.sv.geringfuegigkeit, 2)} im Monat, der Geringfügigkeitsgrenze 2026.` },
      { q: 'Wie genau ist dieser Brutto-Netto-Rechner?', a: `Wir haben ihn am ${h.date(BMF_DATUM)} mit ${BMF_FAELLE} Fällen des amtlichen BMF-Rechners verglichen: ${BMF_BETRAEGE} Bruttobeträge von ${h.eur(BMF_MIN)} bis ${h.eur(BMF_MAX)}, jeweils mit Kindern, geteiltem Familienbonus, Alleinverdienerabsetzbetrag, kleinem und großem Pendlerpauschale und für Wien. Monatliche Sozialversicherung und Lohnsteuer sowie die Abzüge beider Sonderzahlungen stimmen auf den Cent. Die Prüfung läuft vor jeder Veröffentlichung automatisch.` },
      { q: 'Was ist im Netto nicht berücksichtigt?', a: `Sachbezüge wie Dienstwagen oder Dienstwohnung, Überstunden, Betriebsratsumlage und Gewerkschaftsbeitrag, freiwillige Abzüge und alles, was erst die Arbeitnehmerveranlagung bringt: zusätzliche Werbungskosten, Kindermehrbetrag, SV-Rückerstattung bei niedrigem Einkommen. Für Überstunden und das Jahressechstel gibt es eigene Rechner, die Veranlagung erklärt eine eigene Seite.` },
    ],
    body: (h) => `
<h2>So rechnet der Brutto-Netto-Rechner</h2>
<p>Ein österreichischer Lohnzettel hat zwei Welten: den laufenden Bezug, der zwölfmal im Jahr kommt, und die Sonderzahlungen, die nach eigenen Regeln abgerechnet werden. Der Rechner folgt dieser Trennung, Monat für Monat.</p>
<h3>Erstens: die Sozialversicherung</h3>
<p>Vom laufenden Bruttobezug gehen ${h.pct(h.P.sv.dn.kv, 2)} Krankenversicherung, ${h.pct(h.P.sv.dn.pv, 2)} Pensionsversicherung, bis zu ${h.pct(h.P.sv.dn.av, 2)} Arbeitslosenversicherung, ${h.pct(h.P.sv.dn.ak, 1)} Arbeiterkammerumlage und der Wohnbauförderungsbeitrag ab. Zusammen sind das ${h.pct(h.P.sv.dn.kv + h.P.sv.dn.pv + h.P.sv.dn.av + h.P.sv.dn.ak + h.P.sv.dn.wf, 2)} außerhalb Wiens. Bei kleinen Einkommen sinkt der Arbeitslosenversicherungsbeitrag: bis ${h.eur(h.P.sv.av_staffel[0][0])} brutto entfällt er ganz, bis ${h.eur(h.P.sv.av_staffel[1][0])} beträgt er ${h.pct(0.01, 0)}, bis ${h.eur(h.P.sv.av_staffel[2][0])} ${h.pct(0.02, 0)} (${h.src('oegkAv', 'ÖGK, Staffel ab 1.1.2026')}). Über der Höchstbeitragsgrundlage von ${h.eur(h.P.sv.hbg_monat)} im Monat wird nichts mehr verbeitragt, unter der Geringfügigkeitsgrenze von ${h.eur(h.P.sv.geringfuegigkeit, 2)} zahlt der Dienstnehmer gar keine Beiträge (${h.src('oegkWerte', 'ÖGK, veränderliche Werte 2026')}).</p>
<h3>Zweitens: die Lohnsteuer vom laufenden Bezug</h3>
<p>Brutto minus Sozialversicherung ergibt die Bemessungsgrundlage. Der Rechner rechnet sie aufs Jahr hoch, zieht das Werbungskostenpauschale von ${h.eur(h.P.tarif.werbungskostenpauschale)} und gegebenenfalls das Pendlerpauschale ab und wendet den Tarif nach ${h.src('estg33', '§ 33 EStG')} an: 0 % bis ${h.eur(h.P.tarif.grenzen[0])}, 20 % bis ${h.eur(h.P.tarif.grenzen[1])}, 30 % bis ${h.eur(h.P.tarif.grenzen[2])}, 40 % bis ${h.eur(h.P.tarif.grenzen[3])}, 48 % bis ${h.eur(h.P.tarif.grenzen[4])}, 50 % bis eine Million und 55 % darüber. Vom Ergebnis werden zuerst der Familienbonus Plus abgezogen, dann der Verkehrsabsetzbetrag von ${h.eur(h.P.absetzbetraege.verkehrsabsetzbetrag)}, der Alleinverdiener- oder Alleinerzieherabsetzbetrag und der Pendlereuro. Ein Zwölftel davon ist die Lohnsteuer des Monats.</p>
<table class="journal w-full text-sm my-6"><caption class="text-left text-sm text-navy-600 mb-2">Steuertarif 2026 nach § 33 Abs. 1 EStG</caption><thead><tr><th scope="col" class="text-left py-2">Einkommen im Jahr</th><th scope="col" class="text-right py-2">Steuersatz</th></tr></thead><tbody>
<tr><td class="py-1.5">bis ${h.eur(h.P.tarif.grenzen[0])}</td><td class="text-right">0 %</td></tr>
<tr><td class="py-1.5">${h.eur(h.P.tarif.grenzen[0])} bis ${h.eur(h.P.tarif.grenzen[1])}</td><td class="text-right">20 %</td></tr>
<tr><td class="py-1.5">${h.eur(h.P.tarif.grenzen[1])} bis ${h.eur(h.P.tarif.grenzen[2])}</td><td class="text-right">30 %</td></tr>
<tr><td class="py-1.5">${h.eur(h.P.tarif.grenzen[2])} bis ${h.eur(h.P.tarif.grenzen[3])}</td><td class="text-right">40 %</td></tr>
<tr><td class="py-1.5">${h.eur(h.P.tarif.grenzen[3])} bis ${h.eur(h.P.tarif.grenzen[4])}</td><td class="text-right">48 %</td></tr>
<tr><td class="py-1.5">${h.eur(h.P.tarif.grenzen[4])} bis ${h.eur(h.P.tarif.grenzen[5])}</td><td class="text-right">50 %</td></tr>
<tr><td class="py-1.5">über ${h.eur(h.P.tarif.grenzen[5])}</td><td class="text-right">55 %</td></tr></tbody></table>
<h3>Drittens: Urlaubszuschuss und Weihnachtsremuneration</h3>
<p>Für die Sozialversicherung der Sonderzahlungen gelten ein eigener Jahresdeckel von ${h.eur(h.P.sv.hbg_sz_jahr)} und ein niedrigerer Satz, weil weder Arbeiterkammerumlage noch Wohnbauförderung anfallen. Die Lohnsteuer ist fest: die ersten ${h.eur(h.P.sonderzahlungen.freibetrag)} im Jahr sind frei, danach gelten ${S6(h)}, über ${G25(h)} ${S27(h)} und über ${G50(h)} ${S35(h)} (${h.src('estg67', '§ 67 Abs. 1 EStG')}). Ist das Jahressechstel nicht höher als ${h.eur(h.P.sonderzahlungen.freigrenze_sechstel)}, bleiben die Sonderzahlungen ganz steuerfrei. Das betrifft Monatsbezüge bis etwa ${h.eur(h.P.sonderzahlungen.freigrenze_sechstel / 2)}.</p>

<h2>Warum der Monat zählt, nicht nur das Jahr</h2>
<p>Die meisten Rechner nehmen an, dass Sie zwölf gleiche Gehälter und zwei gleiche Sonderzahlungen bekommen. Dann passt beides genau ins Jahressechstel, und die Rechnung ist einfach. Im echten Leben stimmt das oft nicht. Das Sechstel wird bei jeder Auszahlung neu ermittelt: ein Sechstel der bisher bezahlten laufenden Bezüge, aufs Jahr hochgerechnet (${h.src('estg67', '§ 67 Abs. 2 EStG')}). Wer im Juli eine Gehaltserhöhung bekommt, hat im November ein Sechstel, das noch zum Teil auf dem alten Gehalt beruht; ist die Weihnachtsremuneration schon nach dem neuen Gehalt bemessen, ragt ein Stück über das Sechstel hinaus und wird nach dem Tarif besteuert, mit 30 oder 40 Prozent statt 6.</p>
<p>Beim letzten Gehalt des Jahres rechnet die Lohnverrechnung nach (§ 77 Abs. 4a EStG). Wer im Herbst eine Erhöhung bekam, erhält den Teil der Weihnachtsremuneration, der über dem Sechstel lag, meist im Dezember zurück, weil das Kontrollsechstel aus dem ganzen Jahr inzwischen gewachsen ist. Wer dagegen ab dem Sommer in Teilzeit arbeitet, die Weihnachtsremuneration aber nach dem alten Gehalt bekommt, zahlt im Dezember nach: Das Kontrollsechstel ist kleiner als das Sechstel vom November. Bei einem Austritt, in der Elternkarenz oder mit Krankengeld entfällt diese Nachversteuerung. Unser ${h.a('sonderzahlungen', 'Urlaubsgeld- und Weihnachtsgeld-Rechner')} rechnet all das Monat für Monat durch, mit Eintritt, Austritt, Erhöhung, Prämie und regelmäßigen Überstunden. Mehr Hintergrund steht im Ratgeber zum ${h.a('jahressechstel', 'Jahressechstel')} und auf der Seite zum ${h.a('dreizehntes-gehalt', '13. und 14. Gehalt')}. Probieren Sie den Effekt einer Erhöhung hier direkt aus:</p>
<!--mini:sechstel-->

<h2>Pendlerpauschale und Pendlereuro direkt im Lohnzettel</h2>
<p>Wer weit zur Arbeit fährt, bekommt zwei Begünstigungen. Das Pendlerpauschale ist ein Freibetrag, der die Bemessungsgrundlage senkt: ${h.eur(h.P.pendlerpauschale.klein[0][2])} bis ${h.eur(h.P.pendlerpauschale.klein[2][2])} im Jahr, wenn öffentliche Verkehrsmittel zumutbar sind, ${h.eur(h.P.pendlerpauschale.gross[0][2])} bis ${h.eur(h.P.pendlerpauschale.gross[3][2])}, wenn nicht (${h.src('estg16', '§ 16 Abs. 1 Z 6 EStG')}). Der Pendlereuro ist ein Absetzbetrag und zieht seit 2026 ${h.eur(h.P.absetzbetraege.pendlereuro_je_km)} je Kilometer der einfachen Strecke direkt von der Steuer ab, dreimal so viel wie 2025 (${h.src('bmfPresse', 'BMF, Pressemitteilung vom 30.12.2025')}). Beide zählen nur bei mindestens elf Fahrten im Monat voll, bei acht bis zehn zu zwei Dritteln, bei vier bis sieben zu einem Drittel. Die Entfernung und die Zumutbarkeit legt der amtliche ${h.src('bmfPendlerrechner', 'Pendlerrechner des BMF')} fest; was die Pauschale dann netto bringt, zeigt unser ${h.a('pendlerpauschale', 'Pendlerpauschale-Rechner')} für alle sieben Stufen.</p>

<h2>Familienbonus Plus, Alleinverdiener und Kindermehrbetrag</h2>
<p>Der Familienbonus Plus senkt die Lohnsteuer um ${h.eur(h.P.absetzbetraege.familienbonus_monat_u18, 2)} im Monat für jedes Kind unter 18 und um ${h.eur(h.P.absetzbetraege.familienbonus_monat_ue18, 2)} für Kinder ab 18, für die noch Familienbeihilfe bezogen wird. Er kann die Steuer aber nur bis auf null drücken: Wer wenig Lohnsteuer zahlt, nutzt ihn nur zum Teil. Alleinverdienende und Alleinerziehende mit niedriger Steuer bekommen dafür einen Kindermehrbetrag von bis zu ${h.eur(h.P.absetzbetraege.kindermehrbetrag)} je Kind ausbezahlt. Der Alleinverdiener- oder Alleinerzieherabsetzbetrag selbst beträgt ${h.eur(h.P.absetzbetraege.avab_1_kind)} mit einem Kind, ${h.eur(h.P.absetzbetraege.avab_2_kinder)} mit zwei und ${h.eur(h.P.absetzbetraege.avab_je_weiteres_kind)} mehr für jedes weitere. Wie viel davon bei Ihnen wirkt, zeigt der ${h.a('familienbonus', 'Familienbonus-Plus-Rechner')}.</p>

<h2>Wien und die anderen Bundesländer</h2>
<p>Für Arbeitnehmer unterscheidet sich die Abrechnung 2026 genau an einer Stelle: In Wien beträgt der Wohnbauförderungsbeitrag seit 1. Jänner ${h.pct(h.P.sv.dn.wf_wien, 2)} statt ${h.pct(h.P.sv.dn.wf, 1)} (${h.src('wienWbf', 'Stadt Wien')}). Der Rechner fragt deshalb nach dem Bundesland des Arbeitsorts; der Wohnort spielt keine Rolle. Alles Weitere, von der Steuer bis zur Kranken- und Pensionsversicherung, ist bundesweit gleich. Eine eigene Seite zeigt den ${h.a('wien', 'Brutto-Netto-Rechner für Wien')} mit dem Unterschied in Euro. Beim Dienstgeber kommt der Zuschlag zum Dienstgeberbeitrag hinzu, der je Land zwischen ${h.pct(h.P.dienstgeber.dz.oberoesterreich, 2)} und ${h.pct(h.P.dienstgeber.dz.burgenland, 2)} liegt.</p>

<h2>Geprüft gegen den Rechner des Finanzministeriums</h2>
<p>Eine Formel abzuschreiben ist leicht, sie richtig anzuwenden nicht. Wir haben deshalb am ${h.date(BMF_DATUM)} den ${h.src('bmfRechner', 'amtlichen Brutto-Netto-Rechner des BMF')} ${BMF_FAELLE}-mal abgefragt: ${BMF_BETRAEGE} Bruttobeträge zwischen ${h.eur(BMF_MIN)} und ${h.eur(BMF_MAX)}, jeweils ohne Kinder, mit einem und zwei Kindern, mit geteiltem Familienbonus, mit einem Kind über 18, mit Alleinverdienerabsetzbetrag, mit kleinem und großem Pendlerpauschale und für Wien. Sozialversicherung und Lohnsteuer des Monats, beider Sonderzahlungen und das Jahresnetto stimmen in allen Fällen auf den Cent überein. Diese Fälle laufen vor jeder Veröffentlichung als automatische Tests; weicht ein Cent ab, geht die Seite nicht online. Die Einzelheiten stehen in der ${h.a('method', 'Berechnungsmethode')}.</p>

<h2>Was der Rechner nicht weiß</h2>
<ul>
<li>Sachbezüge wie Dienstwagen oder Dienstwohnung, Jobticket und andere Zuwendungen des Arbeitgebers.</li>
<li>Betriebsratsumlage, Gewerkschaftsbeitrag, Pfändungen, Vorschüsse.</li>
<li>Die Arbeitnehmerveranlagung: zusätzliche Werbungskosten, Sonderausgaben, die SV-Rückerstattung bei niedrigem Einkommen und den Kindermehrbetrag. Was sie bringen kann, erklärt die Seite zur ${h.a('arbeitnehmerveranlagung', 'Arbeitnehmerveranlagung')}.</li>
<li>Lehrlinge, Beamte, freie Dienstnehmer und Pensionisten haben eigene Beitragssätze.</li>
</ul>

<h2>Fünf Dinge, die Ihr Netto 2026 erhöhen können</h2>
<ol>
<li>Pendlerpauschale beim Arbeitgeber beantragen: mit dem Ausdruck aus dem Pendlerrechner, sonst kommt sie erst mit der Veranlagung.</li>
<li>Familienbonus richtig aufteilen: Verdient ein Elternteil wenig, bringt die volle Zuordnung beim anderen mehr.</li>
<li>Überstunden prüfen: 2026 sind die Zuschläge für die ersten ${h.P.ueberstunden.frei_stunden_2026} Überstunden bis ${h.eur(h.P.ueberstunden.frei_max_2026)} im Monat steuerfrei (${h.src('estg124b', '§ 124b EStG')}).</li>
<li>Die Arbeitnehmerveranlagung machen, auch wenn sie nicht Pflicht ist; sie ist fünf Jahre rückwirkend möglich.</li>
<li>Bei einer Gehaltserhöhung im Herbst mit der Lohnverrechnung klären, wie hoch die Weihnachtsremuneration bemessen wird.</li>
</ol>
`,
  },
  en: {
    title: 'Gross to Net Austria 2026: Salary After Tax and Insurance',
    description: 'Gross to net calculator Austria 2026 for expats: wage tax, social insurance, 13th and 14th salary with the sixth rule and commuter allowance, checked vs BMF.',
    h1: 'Austrian gross-to-net calculator 2026',
    intro: 'From your gross salary to the money in your account: social insurance, wage tax, holiday pay and Christmas pay, month by month on 2026 values.',
    resume: (h) => `On a gross salary of ${h.eur(3000)} a month, an employee in Upper Austria, Tyrol or Styria takes home ${h.eur(A.nettoMonat, 2)} in 2026: ${h.pct(A.svMonat / 3000, 2)} goes to social insurance and ${h.eur(A.lstMonat, 2)} to wage tax. Austria pays most employees fourteen times a year, and the extra two payments, holiday pay in June and Christmas pay in November, each leave about ${h.eur(Math.round(A.uzNetto / 10) * 10)} net because they are taxed at a flat ${S6(h)} after a ${h.eur(h.P.sonderzahlungen.freibetrag)} allowance. That only works while both fit inside the annual sixth, one sixth of your regular pay; a pay rise during the year or a job that starts in summer moves that line, which most calculators ignore. In 2026 the tax brackets rose by ${h.pct(h.P.tarif.indexierung_2026, 2)}, the commuter euro tripled to ${h.eur(h.P.absetzbetraege.pendlereuro_je_km)} per kilometre, and Vienna raised its housing contribution to ${h.pct(h.P.sv.dn.wf_wien, 2)}. This calculator applies all of it and matches the Finance Ministry calculator to the cent in ${BMF_FAELLE} test cases.`,
    faqs: (h) => [
      { q: 'What is the take-home pay on 3,000 euros gross in Austria?', a: `${h.eur(A.nettoMonat, 2)} a month in every state except Vienna, where it is ${h.eur(W.nettoMonat, 2)} because the housing-subsidy contribution went up to ${h.pct(h.P.sv.dn.wf_wien, 2)} in January 2026. On top come holiday pay and Christmas pay of roughly ${h.eur(Math.round(A.uzNetto / 10) * 10)} net each, so a year brings ${h.eur(A.nettoJahr)} net from ${h.eur(A.bruttoJahr)} gross, without children or commuter allowance, on the 2026 values of the official calculator.` },
      { q: 'Why does Austria pay a 13th and 14th salary?', a: `It is not in the tax law but in almost every collective agreement (Kollektivvertrag): one extra monthly salary as Urlaubszuschuss, usually in June, and one as Weihnachtsremuneration, usually in November. The tax law rewards it: within the annual sixth the first ${h.eur(h.P.sonderzahlungen.freibetrag)} are tax-free and the rest is taxed at ${S6(h)} instead of your normal rate. Job offers in Austria therefore usually quote a monthly salary paid 14 times.` },
      { q: 'Does the federal state change my net pay?', a: `For employees only in Vienna. Since 1 January 2026 the housing-subsidy contribution there is ${h.pct(h.P.sv.dn.wf_wien, 2)} of gross pay instead of ${h.pct(h.P.sv.dn.wf, 1)}, so ${h.eur(WD, 2)} more is deducted on ${h.eur(3000)}. What counts is where you work, not where you live. Tax, health and pension contributions are the same nationwide; employers additionally pay a state-specific surcharge on their family-fund contribution.` },
      { q: 'Are there tax classes in Austria like in Germany?', a: `No. Austria taxes each person individually, so marriage alone does not change your wage tax. What changes it are credits: Familienbonus Plus of ${h.eur(h.P.absetzbetraege.familienbonus_monat_u18, 2)} a month per child under 18, the sole earner or single parent credit of ${h.eur(h.P.absetzbetraege.avab_1_kind)} a year with one child, and the commuter allowance. You claim them with your employer or in the annual tax assessment.` },
      { q: 'At what salary do you start paying income tax in Austria?', a: `Taxable income up to ${h.eur(h.P.tarif.grenzen[0])} a year is tax-free. With 14 payments, the ${h.eur(h.P.tarif.werbungskostenpauschale)} work-expense allowance and the ${h.eur(h.P.absetzbetraege.verkehrsabsetzbetrag)} transport credit, you pay no wage tax up to about ${h.eur(FREI)} gross a month in 2026; at ${h.eur(1800)} it is ${h.eur(B18.lstMonat, 2)}. Social insurance starts much earlier, above the marginal-employment limit of ${h.eur(h.P.sv.geringfuegigkeit, 2)} a month.` },
      { q: 'How accurate is this calculator compared with the official one?', a: `On ${h.date(BMF_DATUM)} we compared it with ${BMF_FAELLE} results of the Finance Ministry calculator: ${BMF_BETRAEGE} gross amounts from ${h.eur(BMF_MIN)} to ${h.eur(BMF_MAX)}, each with and without children, a split Familienbonus, the sole earner credit, small and large commuter allowance, and Vienna. Monthly social insurance and wage tax, the deductions on both special payments and the annual net all match to the cent. These cases run as automatic tests before every update.` },
    ],
    body: (h) => `
<h2>How Austrian payroll gets from gross to net</h2>
<p>An Austrian payslip runs on two tracks. Your regular salary arrives twelve times a year; the special payments, holiday pay and Christmas pay, are settled under their own rules. The calculator keeps those tracks apart and works through the year month by month, the way your employer’s payroll office does.</p>
<h3>Step one: social insurance</h3>
<p>From regular pay your employer deducts ${h.pct(h.P.sv.dn.kv, 2)} health insurance, ${h.pct(h.P.sv.dn.pv, 2)} pension insurance, up to ${h.pct(h.P.sv.dn.av, 2)} unemployment insurance, the ${h.pct(h.P.sv.dn.ak, 1)} Chamber of Labour levy and the housing-subsidy contribution: ${h.pct(h.P.sv.dn.kv + h.P.sv.dn.pv + h.P.sv.dn.av + h.P.sv.dn.ak + h.P.sv.dn.wf, 2)} in total outside Vienna. Low earners pay less unemployment insurance: nothing up to ${h.eur(h.P.sv.av_staffel[0][0])} gross, ${h.pct(0.01, 0)} up to ${h.eur(h.P.sv.av_staffel[1][0])}, ${h.pct(0.02, 0)} up to ${h.eur(h.P.sv.av_staffel[2][0])} (${h.src('oegkAv', 'ÖGK, 2026 scale')}). Above the contribution ceiling of ${h.eur(h.P.sv.hbg_monat)} a month nothing more is charged, and below the marginal-employment limit of ${h.eur(h.P.sv.geringfuegigkeit, 2)} employees pay nothing at all (${h.src('oegkWerte', 'ÖGK, 2026 values')}).</p>
<h3>Step two: wage tax on regular pay</h3>
<p>Gross minus social insurance is your taxable pay. The payroll engine scales it up to a year, subtracts the ${h.eur(h.P.tarif.werbungskostenpauschale)} flat allowance for work expenses and, if you have one, the commuter allowance, then applies the scale in ${h.src('estg33', 'section 33 of the Income Tax Act')}: nothing up to ${h.eur(h.P.tarif.grenzen[0])}, 20% to ${h.eur(h.P.tarif.grenzen[1])}, 30% to ${h.eur(h.P.tarif.grenzen[2])}, 40% to ${h.eur(h.P.tarif.grenzen[3])}, 48% to ${h.eur(h.P.tarif.grenzen[4])}, 50% up to one million and 55% beyond. Credits come off that figure: first Familienbonus Plus, then the ${h.eur(h.P.absetzbetraege.verkehrsabsetzbetrag)} transport credit that every employee gets, the sole earner or single parent credit and the commuter euro. One twelfth is the month’s wage tax.</p>
<h3>Step three: holiday pay and Christmas pay</h3>
<p>Special payments have their own annual contribution ceiling of ${h.eur(h.P.sv.hbg_sz_jahr)} and a lower rate, because neither the Chamber of Labour levy nor the housing contribution applies. The tax is flat: the first ${h.eur(h.P.sonderzahlungen.freibetrag)} a year are free, then ${S6(h)}, rising to ${S27(h)} above ${G25(h)} and ${S35(h)} above ${G50(h)} (${h.src('estg67', 'section 67 of the Income Tax Act')}). If the annual sixth is no more than ${h.eur(h.P.sonderzahlungen.freigrenze_sechstel)}, special payments are entirely tax-free, which covers monthly salaries up to about ${h.eur(h.P.sonderzahlungen.freigrenze_sechstel / 2)}.</p>

<h2>Why the month matters, not just the year</h2>
<p>Most online calculators assume twelve identical salaries and two identical bonuses. Then both payments fit exactly into the annual sixth and the maths is simple. Real careers are messier. The sixth is worked out again at every payment: one sixth of the regular pay received so far, scaled to a full year (${h.src('estg67', 'section 67(2)')}). Get a raise in July and your November sixth still partly rests on the old salary; if your Christmas pay already follows the new one, a slice sticks out above the sixth and is taxed on the normal scale, at 30 or 40 percent instead of 6.</p>
<p>With the last salary of the year, payroll runs a control calculation (section 77(4a)). If you got a raise in autumn, the slice of Christmas pay that went above the sixth usually comes back in December, because the sixth based on the whole year has grown by then. If you switched to part-time in summer but your Christmas pay still follows the old salary, you pay extra in December, because the control sixth is smaller than November’s. Leaving the job, parental leave or sick pay cancel that extra charge. Our ${h.a('sonderzahlungen', 'holiday and Christmas pay calculator')} runs through every month with start date, leaving date, pay rise, bonus and regular overtime. The background is explained on the pages about the ${h.a('jahressechstel', 'annual sixth rule')} and the ${h.a('dreizehntes-gehalt', '13th and 14th salary')}. Try the effect of a raise right here:</p>
<!--mini:sechstel-->

<h2>Commuter allowance and commuter euro inside payroll</h2>
<p>Long commutes earn two tax breaks. The Pendlerpauschale is a deduction that lowers taxable pay: ${h.eur(h.P.pendlerpauschale.klein[0][2])} to ${h.eur(h.P.pendlerpauschale.klein[2][2])} a year when public transport is reasonable, ${h.eur(h.P.pendlerpauschale.gross[0][2])} to ${h.eur(h.P.pendlerpauschale.gross[3][2])} when it is not (${h.src('estg16', 'section 16 of the Income Tax Act')}). The Pendlereuro is a credit worth ${h.eur(h.P.absetzbetraege.pendlereuro_je_km)} per kilometre of the one-way distance since 2026, three times the 2025 amount (${h.src('bmfPresse', 'Finance Ministry, 30 December 2025')}). Both apply in full with at least eleven commutes a month, two thirds with eight to ten and one third with four to seven. The official ${h.src('bmfPendlerrechner', 'Pendlerrechner')} decides the distance and whether public transport counts as reasonable; our ${h.a('pendlerpauschale', 'commuter allowance calculator')} then shows what each of the seven bands is worth to you in net euros.</p>

<h2>Familienbonus Plus, sole earners and the Kindermehrbetrag</h2>
<p>Familienbonus Plus cuts your wage tax by ${h.eur(h.P.absetzbetraege.familienbonus_monat_u18, 2)} a month for each child under 18 and ${h.eur(h.P.absetzbetraege.familienbonus_monat_ue18, 2)} for older children who still receive family allowance. It can only bring your tax down to zero, so low earners use part of it. Sole earners and single parents whose tax is low receive a Kindermehrbetrag of up to ${h.eur(h.P.absetzbetraege.kindermehrbetrag)} per child instead, paid out after the annual assessment. The sole earner or single parent credit itself is ${h.eur(h.P.absetzbetraege.avab_1_kind)} with one child, ${h.eur(h.P.absetzbetraege.avab_2_kinder)} with two and ${h.eur(h.P.absetzbetraege.avab_je_weiteres_kind)} more for each further child. The ${h.a('familienbonus', 'Familienbonus Plus calculator')} shows how much of it works on your salary.</p>

<h2>Vienna and the other states</h2>
<p>For employees, payroll differs in exactly one place in 2026: in Vienna the housing-subsidy contribution is ${h.pct(h.P.sv.dn.wf_wien, 2)} instead of ${h.pct(h.P.sv.dn.wf, 1)} since 1 January (${h.src('wienWbf', 'City of Vienna')}). The calculator therefore asks for the state of your workplace; where you live does not matter. Everything else, from tax to health and pension insurance, is the same nationwide. A separate page shows the ${h.a('wien', 'Vienna gross-to-net calculator')} with the difference in euros. Employers also pay a family-fund surcharge that ranges from ${h.pct(h.P.dienstgeber.dz.oberoesterreich, 2)} to ${h.pct(h.P.dienstgeber.dz.burgenland, 2)} depending on the state.</p>

<h2>Checked against the Finance Ministry calculator</h2>
<p>Copying a formula is easy; applying it correctly is not. On ${h.date(BMF_DATUM)} we queried the ${h.src('bmfRechner', 'official BMF gross-to-net calculator')} ${BMF_FAELLE} times: ${BMF_BETRAEGE} gross amounts between ${h.eur(BMF_MIN)} and ${h.eur(BMF_MAX)}, each without children, with one and two children, with a split Familienbonus, with a child over 18, with the sole earner credit, with small and large commuter allowance, and for Vienna. Monthly social insurance and wage tax, both special payments and the annual net agree to the cent in every case. The cases run as automatic tests before each release; if a single cent differs, the update does not go live. Details are in the ${h.a('method', 'calculation method')}.</p>

<h2>What the calculator does not know</h2>
<ul>
<li>Benefits in kind such as a company car or flat, travel passes and other perks.</li>
<li>Works council levy, union dues, wage garnishments, salary advances.</li>
<li>The annual tax assessment (Arbeitnehmerveranlagung): extra work expenses, special expenses, the social insurance refund for low earners and the Kindermehrbetrag. The page on the ${h.a('arbeitnehmerveranlagung', 'employee tax assessment')} explains what it can bring.</li>
<li>Apprentices, civil servants, freelancers on a free service contract and pensioners have their own rates.</li>
</ul>

<h2>Five ways to raise your net pay in 2026</h2>
<ol>
<li>Claim the commuter allowance with your employer using the Pendlerrechner printout; otherwise it only arrives with the tax assessment.</li>
<li>Split Familienbonus Plus sensibly: if one parent earns little, giving the full amount to the other often brings more.</li>
<li>Check overtime: in 2026 the premiums for the first ${h.P.ueberstunden.frei_stunden_2026} overtime hours are tax-free up to ${h.eur(h.P.ueberstunden.frei_max_2026)} a month (${h.src('estg124b', 'section 124b')}).</li>
<li>File the employee tax assessment even when it is optional; you can do it five years back.</li>
<li>If your raise comes in autumn, ask payroll how your Christmas pay will be calculated.</li>
</ol>
`,
  },
};
