import { defineGuide } from '../../lib/guide-types';
import { abfertigungAlt, kurz } from '../../lib/engine/leistungen';
import { P, DE, EN } from '../../lib/fmt';

const AB = P.abfertigung;
const ST = AB.alt_staffel;
const MIN_J = ST[0][0], MIN_M = ST[0][1], MAX_J = ST[ST.length - 1][0], MAX_M = ST[ST.length - 1][1];
/** Beispiel: 3.500 € brutto, 15 Dienstjahre, aus dem Motor. */
const b15 = abfertigungAlt(3500, 15);
const sofort = Math.min(b15.brutto, b15.monatsentgelt * 3);
const rest = b15.brutto - sofort;
const tabelle = ST.map(([j]) => ({ j, r: abfertigungAlt(3500, j) }));
/** Vervielfachermethode (§ 67 Abs. 3 EStG): laufende Tariflohnsteuer mal Zahl der Monatsentgelte, wenn niedriger als 6 %. */
const vv = (b: number, j: number) => { const a = abfertigungAlt(b, j); return { a, vv: kurz(b).lstMonat * a.monate }; };
const klein = vv(2000, 15);
/** Höchstes Monatsbrutto (50-€-Schritte), bei dem die Vervielfachermethode bei 15 Jahren günstiger ist. */
let grenze = 1000;
while (grenze < 6000) { const x = vv(grenze + 50, 15); if (x.vv >= x.a.lst6) break; grenze += 50; }

export default defineGuide({
  id: 'abfertigung-alt',
  group: 'leistungen',
  order: 70,
  mini: 'abfertigungAlt',
  miniHref: 'abfertigung',
  related: ['abfertigung', 'abfertigung-neu', 'sonderzahlungen', 'arbeitslosengeld', 'lohnsteuer'],
  sources: ['angg23', 'estg67', 'uspAbfertigung'],
  de: {
    slug: 'abfertigung-alt',
    nav: 'Abfertigung alt',
    card: `${MIN_M} bis ${MAX_M} Monatsentgelte nach § 23 Angestelltengesetz: Anspruch, Fälligkeit, Tod und Steuer.`,
    title: 'Abfertigung alt 2026: Monatsentgelte, Anspruch und Steuer',
    description: `Abfertigung alt 2026: ${MIN_M} bis ${MAX_M} Monatsentgelte samt Sonderzahlungen nach § 23 AngG, wann der Anspruch verfällt, wann sie fällig ist und wie viel Steuer anfällt.`,
    h1: 'Abfertigung alt: Ihr Anspruch nach dem Angestelltengesetz',
    intro: 'Für Dienstverhältnisse, die vor 2003 begonnen haben, zahlt der Arbeitgeber selbst: ein Vielfaches Ihres letzten Monatsentgelts, gestaffelt nach Dienstjahren.',
    resume: `Die Abfertigung alt steht Angestellten zu, deren Dienstverhältnis vor dem 1. Jänner 2003 begonnen hat und ununterbrochen mindestens ${MIN_J} Jahre gedauert hat. Sie beträgt nach § 23 Angestelltengesetz das Zweifache des Entgelts für den letzten Monat und steigt nach ${ST[1][0]} Dienstjahren auf das Dreifache, nach ${ST[2][0]} auf das Vierfache, nach ${ST[3][0]} auf das Sechsfache, nach ${ST[4][0]} auf das Neunfache und nach ${MAX_J} auf das Zwölffache. Zum Monatsentgelt gehören die Sonderzahlungen anteilig, bei 14 Bezügen also ein Sechstel mehr. Wer zuletzt ${DE.eur(3500)} brutto verdient und 15 Jahre im Unternehmen war, bekommt ${b15.monate} Monatsentgelte zu ${DE.eur(b15.monatsentgelt, 2)}, zusammen ${DE.eur(b15.brutto)} brutto und nach ${DE.pct(AB.steuersatz)} Lohnsteuer ${DE.eur(b15.netto)}. Der Anspruch entfällt, wenn Sie selbst kündigen, ohne wichtigen Grund austreten oder verschuldet entlassen werden. Bis zu drei Monatsentgelte sind mit dem Ende fällig, der Rest darf ab dem vierten Monat in monatlichen Raten gezahlt werden. Stirbt der Angestellte, erhalten die unterhaltsberechtigten gesetzlichen Erben die Hälfte.`,
    faqs: [
      { q: 'Wann verliere ich den Anspruch auf die Abfertigung alt?', a: 'Wenn Sie selbst kündigen, ohne wichtigen Grund vorzeitig austreten oder Sie ein Verschulden an der Entlassung trifft (§ 23 Abs. 7 AngG). Erhalten bleibt sie bei Kündigung durch den Arbeitgeber, einvernehmlicher Auflösung, unverschuldeter Entlassung, berechtigtem Austritt und Ablauf einer Befristung. Laut Unternehmensserviceportal gibt es auch bei Selbstkündigung zum Pensionsantritt nach mindestens zehn Jahren einen Anspruch.' },
      { q: 'Wann muss der Arbeitgeber die Abfertigung alt auszahlen?', a: `Bis zur Höhe von drei Monatsentgelten wird sie mit der Auflösung des Dienstverhältnisses fällig. Den Rest darf der Arbeitgeber ab dem vierten Monat in monatlichen, im Voraus zahlbaren Teilbeträgen abstatten (§ 23 Abs. 4 AngG). Bei ${DE.eur(3500)} brutto und 15 Dienstjahren sind ${DE.eur(sofort)} sofort fällig, die übrigen ${DE.eur(rest)} dürfen in monatlichen Teilbeträgen folgen.` },
      { q: 'Was zählt bei der Abfertigung alt zum Monatsentgelt?', a: `Das Entgelt, das Ihnen für den letzten Monat des Dienstverhältnisses gebührt, samt dem anteiligen Urlaubs- und Weihnachtsgeld. Bei zwei Sonderzahlungen ist das Monatsentgelt ein Sechstel höher als das Gehalt: aus ${DE.eur(3500)} werden ${DE.eur(b15.monatsentgelt, 2)}. Endet das Dienstverhältnis während einer Elternteilzeit durch den Arbeitgeber oder einvernehmlich, wird die frühere Normalarbeitszeit zugrunde gelegt (§ 23 Abs. 8 AngG).` },
      { q: 'Wie viel Abfertigung alt bekommen die Hinterbliebenen?', a: `Die Hälfte dessen, was dem Angestellten nach seinen Dienstjahren zugestanden wäre, und nur für die gesetzlichen Erben, zu deren Unterhalt er verpflichtet war (§ 23 Abs. 6 AngG), etwa Ehepartner oder unterhaltsberechtigte Kinder. Nach 15 Jahren bei ${DE.eur(3500)} brutto wären das ${DE.eur(b15.brutto / 2)} statt ${DE.eur(b15.brutto)}. Andere Erben gehen leer aus.` },
      { q: `Wird die Abfertigung alt immer mit ${DE.pct(AB.steuersatz)} versteuert?`, a: `Nein, ${DE.pct(AB.steuersatz)} ist die Obergrenze. Nach § 67 Abs. 3 EStG wird auch die Lohnsteuer des laufenden Monatsbezugs mit der Zahl der Monatsentgelte vervielfacht, und die niedrigere Steuer gilt. Bei ${DE.eur(2000)} brutto und 15 Jahren ergibt das ${DE.eur(klein.vv, 2)} statt ${DE.eur(klein.a.lst6, 2)}. In unserem Motor ist diese Methode bis etwa ${DE.eur(grenze)} Monatsbrutto günstiger. Den Vergleich rechnet die Lohnverrechnung automatisch.` },
      { q: 'Zählen Lehrjahre bei der Abfertigung alt mit?', a: 'Ja, aber nur unter einer Bedingung. Zeiten, die Sie unmittelbar davor als Arbeiter oder Lehrling beim selben Arbeitgeber verbracht haben, werden angerechnet; die Lehrzeit allerdings nur, wenn das Dienstverhältnis einschließlich Lehre mindestens sieben Jahre ununterbrochen gedauert hat. Eine Lehrzeit allein begründet keinen Anspruch (§ 23 Abs. 1 AngG).' },
    ],
    body: (h) => `
<h2>Die Staffel nach Dienstjahren</h2>
${h.table(['ab Dienstjahren', 'Monatsentgelte', `brutto bei ${h.eur(3500)}`, `Lohnsteuer ${h.pct(h.P.abfertigung.steuersatz)}`, 'netto'], tabelle.map(({ j, r }) => [String(j), String(r.monate), h.eur(r.brutto), h.eur(r.lst6), h.eur(r.netto)]), `Abfertigung alt nach ${h.src('angg23', '§ 23 Abs. 1 AngG')}, Monatsentgelt mit einem Sechstel für Sonderzahlungen, aus unserem Motor`, ['r', 'r', 'r', 'r', 'r'])}
<p>Die Abfertigung springt an jeder Schwelle. Wer nach vier Jahren und elf Monaten gekündigt wird, bekommt ${MIN_M} Monatsentgelte, einen Monat später ${ST[1][1]}. Deshalb lohnt es sich, bei einer einvernehmlichen Auflösung kurz vor einem Jubiläum genau auf das Enddatum zu achten. Gezählt wird ab dem Beginn des Dienstverhältnisses bis zu seinem rechtlichen Ende, also einschließlich der Kündigungsfrist.</p>
<p>Maßgeblich ist das Entgelt des letzten Monats, nicht ein Durchschnitt der Dienstjahre. Wer kurz vor dem Ende in Teilzeit gewechselt ist, bekommt die Abfertigung daher vom niedrigeren Monatsentgelt; nur für die Elternteilzeit schreibt § 23 Abs. 8 die frühere Normalarbeitszeit vor. Eine geringfügige Beschäftigung, die Sie während einer Karenz beim selben Arbeitgeber ausgeübt haben, bleibt bei der Berechnung außer Betracht (§ 23 Abs. 1a).</p>
<h2>Wann der Anspruch entsteht und wann er verloren geht</h2>
<p>Das ${h.src('uspAbfertigung', 'Unternehmensserviceportal')} zählt die Beendigungsarten auf, die den Anspruch wahren: Kündigung durch den Arbeitgeber, ungerechtfertigte oder unverschuldete Entlassung, berechtigter vorzeitiger Austritt, einvernehmliche Auflösung, Zeitablauf und Tod. Keinen Anspruch haben Sie nach eigener Kündigung, nach einem Austritt ohne wichtigen Grund und nach einer verschuldeten Entlassung. Ausnahmen von der Selbstkündigung gelten bei einer Kündigung während der Elternteilzeit (dann die Hälfte, höchstens drei Monatsentgelte, wenn das Dienstverhältnis fünf Jahre gedauert hat) und bei Kündigung zum Antritt der Regel- oder Korridorpension nach mindestens zehn Jahren.</p>
<p>Zwei weitere Fälle stehen im Gesetz selbst. Wird das Unternehmen aufgelöst und hat sich die wirtschaftliche Lage des Arbeitgebers so verschlechtert, dass ihm die Zahlung nicht zugemutet werden kann, kann die Abfertigung ganz oder teilweise entfallen (§ 23 Abs. 2). Wird der Betrieb übertragen und lehnen Sie die Fortsetzung ab, obwohl der Erwerber Ihnen dieselben Bedingungen und die Anrechnung Ihrer Dienstzeit anbietet, entfällt sie ebenfalls (§ 23 Abs. 3).</p>
<h2>Austritt nach der Karenz</h2>
<p>Wer nach der Geburt eines Kindes nicht zurückkehren will, kann während der Karenz den vorzeitigen Austritt erklären, bei einer Karenz von mindestens drei Monaten spätestens drei Monate vor ihrem Ende. Dann gebührt die Hälfte der Abfertigung, höchstens drei Monatsentgelte, wenn das Dienstverhältnis ohne die Karenzzeiten mindestens fünf Jahre gedauert hat. Berechnet wird sie vom Entgelt des letzten Monats vor der Karenz.</p>
<!--mini:abfertigungAlt-->
<h2>Fälligkeit: was sofort kommt und was in Raten</h2>
<p>Am Beispiel mit ${h.eur(3500)} und 15 Jahren: Die Abfertigung beträgt ${h.eur(b15.brutto)}. Mit dem Ende des Dienstverhältnisses sind drei Monatsentgelte fällig, also ${h.eur(sofort)}. Die restlichen ${h.eur(rest)} darf der Arbeitgeber ab dem vierten Monat in monatlichen Teilbeträgen zahlen, jeweils im Voraus. Ob Sie danach ${h.a('arbeitslosengeld', 'Arbeitslosengeld')} beantragen, ändert an diesen Fristen nichts; es richtet sich nach Ihren Beitragsgrundlagen, nicht nach der Abfertigung.</p>
<h2>Die Lohnsteuer: ${h.pct(h.P.abfertigung.steuersatz)} oder die Vervielfachermethode</h2>
<p>Gesetzliche Abfertigungen werden nach ${h.src('estg67', '§ 67 Abs. 3 EStG')} besteuert. Das Finanzamt kennt zwei Rechenwege und nimmt den günstigeren: entweder ${h.pct(h.P.abfertigung.steuersatz)} vom Abfertigungsbetrag, oder die tarifmäßige Lohnsteuer des laufenden Monatslohns mal der Zahl der Monatsentgelte. Bei kleinen Gehältern, deren laufende Lohnsteuer unter ${h.pct(h.P.abfertigung.steuersatz)} des Monatsentgelts liegt, gewinnt die zweite Methode. Bei ${h.eur(2000)} brutto und ${klein.a.monate} Monatsentgelten zahlen Sie so ${h.eur(klein.vv, 2)} statt ${h.eur(klein.a.lst6, 2)}. Darüber bleibt es bei ${h.pct(h.P.abfertigung.steuersatz)}. Die Abfertigung wird nach Abs. 3 eigenständig besteuert, nicht über das Jahressechstel des Abs. 1 und 2. Was danach mit dem regulären ${h.a('sonderzahlungen', 'Urlaubs- und Weihnachtsgeld')} im Austrittsjahr passiert, rechnet die Lohnverrechnung getrennt.</p>
<h2>Übertritt ins neue System</h2>
<p>Hat Ihr Arbeitgeber Ihnen den Wechsel in die ${h.a('abfertigung-neu', 'Abfertigung neu')} angeboten, gibt es zwei Varianten. Beim Einfrieren bleibt die bis zum Stichtag erworbene Zahl an Monatsentgelten nach altem Recht bestehen, berechnet später vom letzten Monatsentgelt, und geht weiterhin bei Selbstkündigung verloren. Bei der Übertragung wird sie in einen Kapitalbetrag umgerechnet und in die Vorsorgekasse eingezahlt; danach gelten nur noch die Regeln des neuen Systems. Beide Teile rechnen Sie mit dem ${h.a('abfertigung', 'Abfertigungsrechner')} getrennt nach.</p>
`,
  },
  en: {
    slug: 'old-severance-scheme',
    nav: 'Old severance scheme',
    card: `${MIN_M} to ${MAX_M} months of pay under section 23 of the Salaried Employees Act: entitlement, timing, death and tax.`,
    title: 'Abfertigung alt 2026: Months of Pay, Entitlement and Tax',
    description: `Abfertigung alt 2026: ${MIN_M} to ${MAX_M} months' pay including special payments under section 23 AngG, when you lose it, when it is due and why tax is ${EN.pct(AB.steuersatz)} at most.`,
    h1: 'The old severance scheme: your claim under the Salaried Employees Act',
    intro: 'For jobs that began before 2003 the employer pays severance directly: a multiple of your last monthly pay, stepped by years of service.',
    resume: `The old severance scheme (Abfertigung alt) covers salaried employees in Austria whose job began before 1 January 2003 and has lasted without a break for at least ${MIN_J} years. Under section 23 of the Salaried Employees Act (Angestelltengesetz, AngG) it equals twice the pay due for the last month, rising to three times after ${ST[1][0]} years of service, four times after ${ST[2][0]}, six after ${ST[3][0]}, nine after ${ST[4][0]} and twelve after ${MAX_J}. Monthly pay includes a share of the special payments, so with the usual 14 salaries a year it is one sixth higher than the monthly salary. If you last earned ${EN.eur(3500)} gross and spent 15 years with the firm, you receive ${b15.monate} months at ${EN.eur(b15.monatsentgelt, 2)}, ${EN.eur(b15.brutto)} gross and ${EN.eur(b15.netto)} after ${EN.pct(AB.steuersatz)} wage tax. You lose it if you resign, walk out without good cause or are dismissed for misconduct. Up to three months' pay is due when the job ends; the rest may be paid in monthly instalments from the fourth month. If the employee dies, the legal heirs he or she had to support receive half.`,
    faqs: [
      { q: 'When do I lose my old-scheme severance claim?', a: 'If you resign, leave early without good cause or are dismissed through your own fault (section 23(7) AngG). You keep it if the employer gives notice, you agree a mutual termination (einvernehmliche Auflösung), you are dismissed without fault, you leave for good cause or a fixed term runs out. According to the Business Service Portal, resigning to take up a pension after at least ten years also keeps the claim.' },
      { q: 'When must my employer pay old-scheme severance?', a: `Up to three months' pay falls due when the job ends. The employer may pay the rest in monthly instalments, payable in advance, from the fourth month (section 23(4) AngG). On ${EN.eur(3500)} gross after 15 years, ${EN.eur(sofort)} are due at once and the remaining ${EN.eur(rest)} may follow in monthly instalments. Nothing stops the employer from paying it all at once with the final settlement (Endabrechnung).` },
      { q: 'What counts as monthly pay for old-scheme severance?', a: `The pay due for the last month of employment plus the pro-rata share of holiday and Christmas pay. With two special payments, monthly pay is one sixth higher than salary: ${EN.eur(3500)} becomes ${EN.eur(b15.monatsentgelt, 2)}. If the job ends during parental part-time through the employer or by mutual agreement, your earlier normal working hours are used instead (section 23(8) AngG).` },
      { q: 'How much old-scheme severance do surviving family members receive?', a: `Half of what the employee would have received for their years of service, and only for the legal heirs the employee was obliged to support (section 23(6) AngG), such as a spouse or children still dependent on them. After 15 years on ${EN.eur(3500)} gross that would be ${EN.eur(b15.brutto / 2)} instead of ${EN.eur(b15.brutto)}. Other heirs receive nothing from it.` },
      { q: `Is old-scheme severance always taxed at ${EN.pct(AB.steuersatz)}?`, a: `No, ${EN.pct(AB.steuersatz)} is the ceiling. Under section 67(3) of the Income Tax Act the wage tax on one regular month is also multiplied by the number of months' pay, and the lower figure applies. On ${EN.eur(2000)} gross after 15 years that gives ${EN.eur(klein.vv, 2)} instead of ${EN.eur(klein.a.lst6, 2)}. In our engine this multiplier method wins up to about ${EN.eur(grenze)} a month. Payroll compares both automatically.` },
      { q: 'Do apprenticeship years count towards old-scheme severance?', a: 'Yes, with one condition. Time you spent immediately before as a blue-collar worker or apprentice with the same employer counts, but apprenticeship years only if the employment including the apprenticeship lasted at least seven years without a break. An apprenticeship on its own never creates a claim (section 23(1) AngG).' },
    ],
    body: (h) => `
<h2>The scale by years of service</h2>
${h.table(['From year', 'Months of pay', `Gross on ${h.eur(3500)}`, `Wage tax ${h.pct(h.P.abfertigung.steuersatz)}`, 'Net'], tabelle.map(({ j, r }) => [String(j), String(r.monate), h.eur(r.brutto), h.eur(r.lst6), h.eur(r.netto)]), `Old-scheme severance under ${h.src('angg23', 'section 23(1) AngG')}, monthly pay plus one sixth for special payments, from our engine`, ['r', 'r', 'r', 'r', 'r'])}
<p>Severance jumps at each threshold. If your job ends after four years and eleven months you get ${MIN_M} months' pay; a month later, ${ST[1][1]}. When negotiating a mutual termination shortly before an anniversary, the end date is worth checking carefully. Service counts from the start of employment to its legal end, notice period included.</p>
<p>What counts is the pay for the last month, not an average over your career. If you moved to part-time shortly before the end, severance is based on the lower monthly pay; only for parental part-time does section 23(8) require your earlier normal hours. A marginal job you held with the same employer during parental leave is ignored in the calculation (section 23(1a)).</p>
<h2>When the claim arises and when it is lost</h2>
<p>The ${h.src('uspAbfertigung', 'Business Service Portal')} lists the ways a job can end without losing severance: notice from the employer, unjustified or blameless dismissal, justified early departure, mutual termination, expiry of a fixed term and death. There is no claim after you resign, after leaving early without good cause and after dismissal for misconduct. Resigning still keeps a claim in two cases: during parental part-time (half, capped at three months' pay, if the job lasted five years) and to take up a regular or corridor pension after at least ten years.</p>
<p>Two further cases are in the Act itself. If the business is wound up and the employer's finances have deteriorated so much that payment cannot fairly be expected, severance may be reduced or cancelled (section 23(2)). If the business is sold and you refuse to continue although the buyer offers the same terms and credits your service, the claim lapses too (section 23(3)).</p>
<h2>Leaving after parental leave</h2>
<p>If you decide not to return after having a child, you can declare early departure during parental leave (Karenz), for leave of at least three months no later than three months before it ends. You then receive half of the severance, at most three months' pay, provided the job lasted at least five years not counting the leave. It is based on the pay for the last month before the leave began.</p>
<!--mini:abfertigungAlt-->
<h2>Timing: what comes at once and what in instalments</h2>
<p>Take ${h.eur(3500)} and 15 years: severance is ${h.eur(b15.brutto)}. Three months' pay, ${h.eur(sofort)}, is due when the job ends. The remaining ${h.eur(rest)} may be paid in monthly instalments from the fourth month, each in advance. If you go on to claim ${h.a('arbeitslosengeld', 'unemployment benefit')}, its daily rate is based on your contribution records, not on the severance.</p>
<h2>Wage tax: ${h.pct(h.P.abfertigung.steuersatz)} or the multiplier method</h2>
<p>Statutory severance is taxed under ${h.src('estg67', 'section 67(3) of the Income Tax Act')}. There are two ways to calculate it and the cheaper one applies: either ${h.pct(h.P.abfertigung.steuersatz)} of the severance, or the scale wage tax on one regular month multiplied by the number of months' pay. On small salaries, where regular wage tax is below ${h.pct(h.P.abfertigung.steuersatz)} of monthly pay, the second method wins. At ${h.eur(2000)} gross and ${klein.a.monate} months you pay ${h.eur(klein.vv, 2)} instead of ${h.eur(klein.a.lst6, 2)}. Above that it stays at ${h.pct(h.P.abfertigung.steuersatz)}. Severance is taxed on its own under subsection 3, not through the annual sixth of subsections 1 and 2 that governs your ${h.a('sonderzahlungen', 'holiday and Christmas pay')}.</p>
<h2>Switching to the new scheme</h2>
<p>If your employer offered a move to the ${h.a('abfertigung-neu', 'new severance scheme')}, there are two variants. Freezing keeps the number of months earned under the old rules up to the switch date, calculated later from your last monthly pay, and it is still lost if you resign. Transfer converts it into a lump sum paid into the provision fund, after which only the new rules apply. You can model both parts separately in the ${h.a('abfertigung', 'severance calculator')}.</p>
`,
  },
});
